### ISSUE TITLE
does the map created earlier?

### ISSUE THREAD

**Issue by naveeen0308** [suhasnagaraj99/Autonomous-Mobile-Robot-Navigation#1]
In my previous learning of ros2 nav2 stack and i implemented a pre-built gazebo world where the robo will travel around without hitting any obstacles. In which i have created a map earlier itself and using it while navigating the robot in gazebo world. Could you please confirm that, how did you done in this project? Is there any posibility to create the map and navigation at the same time in ros2 ?

**Comment by suhasnagaraj99** [comment]
This project was done in 2 phases, mapping phase and navigation phase. During the mapping phase, a detailed map of the environment was created and saved. In the navigation phase, the map was loaded and waypoints were given.
You can attempt to do both together, where the robot builds the map as it tries to reach a waypoint by avoiding obstacles, but this might not give you an optimal path as the robot will be exploring unmapped region in real time.
